---
aliases:
  - 仿真
  - simulation
  - simpy
date: 2024-12-29
---

# 前言

今天晚上本来是想复习一下之前学习的仿真，但是不管是打开笔记还是代码，发现都无从下手。遂决定重新开一个文件夹重新梳理一下仿真，避免以后需要用的时候又一头雾水的情况。

# 目标

和学[[编程/前端/JavaScript/Vue/00前言|Vue]]一样，学习前先明确自己的学习目标，要学哪些内容，要达到什么样的程度。

2024/12/29~2025/1/5 这一周内做到能够在不看教程的情况下把 Simpy in 10 minutes 的例子实现一遍。

# 流程

- 创建环境
- 启动进程函数
- 运行仿真

# 资源

多个进程使用容量有限的资源

创建资源
等待资源
占用资源
释放资源


在 SimPy 中，`Resource` 并不是必须等到所有资源都被释放后，进程才能使用。每个资源都有一个容量（capacity），表示同时可以被多少个进程使用。当一个进程请求资源时，如果资源有空闲容量，它就可以立即使用该资源；如果没有空闲容量，进程将会等待，直到有资源被释放。

以下是一个简单的示例，展示了如何在 SimPy 中使用 `Resource`：

```python


import simpy

def process(env, resource, name):
    print(f'{name} requesting resource at {env.now}')
    with resource.request() as req:
        yield req
        print(f'{name} acquired resource at {env.now}')
        yield env.timeout(2)
        print(f'{name} released resource at {env.now}')

env = simpy.Environment()
resource = simpy.Resource(env, capacity=1)

env.process(process(env, resource, 'Process 1'))
env.process(process(env, resource, 'Process 2'))
env.run(until=5)
```

在这个示例中：
- 创建了一个容量为1的资源。
- 两个进程请求资源并使用它，每个进程使用资源2个时间单位。
- 由于资源的容量为1，第二个进程必须等待第一个进程释放资源后才能使用。

这样可以看到，资源的使用是基于其容量的，而不是必须等到所有资源都被释放后才能使用。

# 事件

[[基础#事件|在 simpy 中事件有 3 种状态]]，即未触发，已触发，已处理。之前在看[Events — SimPy 4.1.2.dev8+g81c7218 documentation|官方文档例子时，被一个关于事件的例子卡了很久](https://simpy.readthedocs.io/en/latest/topical_guides/events.html)。我们知道 Simpy 在运行进程函数的过程中，执行到 yield 语句时，进程函数会被挂起，只有当事件的状态变为已处理后，进程函数才会被恢复，并继续执行后续的代码。

这里就存在一个问题：当事件的状态变为已处理时，进程函数立马会被恢复吗？

应该分为两种情况：

第一种情况，如果是传统的 yield env.timeout(delay)，那么当计时结束之后，进程函数立马就会被恢复，换句话说，事件的状态是在当前的进程函数中变化的，那么进程函数立马就会被恢复
第二种情况，如果是事件的状态被另外一个进程函数控制，就需要等另外一个进程函数运行完或者再次被挂起时，当前的进程函数才会被恢复（控制权还没交到自己手上）

```Python
import simpy

  
  

class School:

    def __init__(self, env):

        self.env = env

        self.class_ends = env.event()

        self.pupil_procs = [env.process(self.pupil()) for i in range(3)]

        self.bell_proc = env.process(self.bell())

  

    def bell(self):

        for i in range(2):

            yield self.env.timeout(45)

            self.class_ends.succeed()

            self.class_ends = self.env.event()

            print("bbb")

  

    def pupil(self):

        for i in range(2):

            print(" \o/", end="")

            yield self.class_ends # 多个进程函数等同一个事件

            print("aaa", end=" ")

  
  

env = simpy.Environment()

school = School(env)

env.run()
```

输出

```
 \o/ \o/ \o/bbb
aaa  \o/aaa  \o/aaa  \o/bbb
aaa aaa aaa

说明：
aaa  \o/ aaa  \o/ aaa  \o/
```

逐行代码分析：

- School  的构造方法
	- 定义了一个 env 属性，用于保存 env
	- 定义了一个 class_ends 属性，用于保存一个下课的事件
	- 定义了一个 pupil_process 属性，启动三个 pupil 进程函数
		- 第一个 pupil 进程函数，先打印 `\o/`，遇到 yield 挂起
		- 第二个 pupil 进程函数，先打印 `\o/`，遇到 yield 挂起
		- 第三个 pupil 进程函数，先打印 `\o/`，遇到 yield 挂起
	- 定义了一个 bell 属性，启动 bell 进程函数
		- 遇到 yield，bell 进程函数被挂起，等了 45 个时间单位，bell 进程函数被恢复
		- 改变下课事件的状态，重新给 class_ends 的属性赋值
		- 打印 bbb
		- 第二次遇到 yield，bell 进程函数被挂起
	- 原来的下课事件已变为 succeed，第一个 pupil 进程函数被恢复，先打印 aaa，再打印 `\o/`，遇到 yield 挂起
	- 原来的下课事件已变为 succeed，第二个 pupil 进程函数被恢复，先打印 aaa，再打印 `\o/`，遇到 yield 挂起
	- 原来的下课事件已变为 succeed，第三个 pupil 进程函数被恢复，先打印 aaa，再打印 `\o/`，遇到 yield 挂起
	- 等了 45 个时间单位后 bell 进程函数被恢复
	- 改变下课事件的状态，重新给 class_ends 的属性赋值
	- 打印 bbb
	- 原来的下课事件已变为 succeed，第一个 pupil 进程函数被恢复，先打印 aaa，但是由于循环已结束，第一个 pupil 进程函数执行结束
	- 原来的下课事件已变为 succeed，第二个 pupil 进程函数被恢复，先打印 aaa，但是由于循环已结束，第二个 pupil 进程函数执行结束
	- 原来的下课事件已变为 succeed，第三个 pupil 进程函数被恢复，先打印 aaa，但是由于循环已结束，第三个 pupil 进程函数执行结束

